export const sportsListMapping = {
  '': 'defaultImage.jpeg',
  Football: 'football.jpeg',
  Basketball: 'basketball.jpeg',
  Tennis: 'tennis.jpeg',
  Golf: 'golf.jpeg',
  Natation: 'natation.jpeg',
  Athlétisme: 'athletisme.jpeg',
  Cyclisme: 'cyclisme.jpeg',
  'Volley-ball': 'volley-ball.jpeg',
  Baseball: 'baseball.jpeg',
  Boxe: 'boxe.jpeg',
  Escalade: 'escalade.jpeg',
  'Hockey sur glace': 'hockey-sur-glace.jpeg',
  Rugby: 'rugby.jpeg',
  Badminton: 'badminton.jpeg',
  'Course automobile': 'course-automobile.jpeg',
  'Ski alpin': 'ski-alpin.jpeg',
  Escrime: 'escrime.jpeg',
  Gymnastique: 'gymnastique.jpeg',
  Musculation: 'musculation.jpeg',
  Judo: 'judo.jpeg',
  Surf: 'surf.jpeg',
  'Planche à voile': 'planche-voile.jpeg',
  'Water-polo': 'water-polo.jpeg',
  'Tir à l\'arc': 'tir-arc.jpeg',
  Haltérophilie: 'halterophilie.jpeg',
  Handball: 'handball.jpeg',
  Karaté: 'karate.jpeg',
  Taekwondo: 'taekwondo.jpeg',
  Wrestling: 'wrestling.jpeg'
} as const

export type SportsListMappingKey = keyof typeof sportsListMapping
