name: ESLint Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm --force install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true # Continue même en cas d'erreur

      - name: Check ESLint Status
        run: |
          if [ ${{ job.status }} != "completed" ]; then
            echo "ESLint check failed. Cancelling the workflow..."
            exit 1
          fi
