name: ESLint Check

on:
  push:
    branches:
      - main # Déclenchez le workflow lorsque des modifications sont poussées sur la branche principale (changez-la selon vos besoins)

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Choisissez la version de Node.js dont vous avez besoin

      - name: Install Dependencies
        run: npm install # Assurez-vous d'installer ESLint et toutes les dépendances nécessaires

      - name: Run ESLint
        run: npm run lint # Assurez-vous que vous avez une commande de lint configurée dans votre projet
